//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bedenler
    {
        public int ID { get; set; }
        public string Beden1 { get; set; }
        public string Beden2 { get; set; }
        public string Beden3 { get; set; }
        public string Beden4 { get; set; }
        public string Beden5 { get; set; }
        public string Beden6 { get; set; }
        public string Beden7 { get; set; }
        public string Beden8 { get; set; }
        public string Beden9 { get; set; }
        public string Beden10 { get; set; }
        public string BedenAdi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public string Company_Code { get; set; }
    }
}
