//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cari
    {
        public int ID { get; set; }
        public string FirmaKodu { get; set; }
        public string KTipi { get; set; }
        public string CariUnvan { get; set; }
        public string VergiDr { get; set; }
        public string VergiNo { get; set; }
        public string Yetkili { get; set; }
        public string TCNo { get; set; }
        public string paraBirimi { get; set; }
        public Nullable<decimal> Iskonto { get; set; }
        public string CariGrubu { get; set; }
        public string Fotograf { get; set; }
        public string Adres { get; set; }
        public string Telefon1 { get; set; }
        public string GSM { get; set; }
        public string Faks { get; set; }
        public string EPosta { get; set; }
        public string WebSite { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Ulke { get; set; }
        public string PostaKodu { get; set; }
        public string Cinsiyet { get; set; }
        public string DogumT { get; set; }
        public string Milleti { get; set; }
        public string MedeniH { get; set; }
        public string EkBilgi { get; set; }
        public string ozelAlan1 { get; set; }
        public string ozelAlan2 { get; set; }
        public string ozelAlan3 { get; set; }
        public string ozelAlan4 { get; set; }
        public string ozelAlan5 { get; set; }
        public string KayitT { get; set; }
        public string DegT { get; set; }
        public Nullable<bool> CariList { get; set; }
        public Nullable<int> MusteriTemsilcisi { get; set; }
        public Nullable<int> OzelKodID { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public string MersisNo { get; set; }
        public string TicaretSicilNo { get; set; }
        public string BagkurNo { get; set; }
        public Nullable<int> DateVade { get; set; }
        public string StokFG { get; set; }
        public string WebKA { get; set; }
        public string WebSifre { get; set; }
        public Nullable<int> TedCariID { get; set; }
        public Nullable<bool> Aktarildi { get; set; }
        public string EkAlan { get; set; }
        public string FirmaURL { get; set; }
        public string SevkAdresi { get; set; }
        public string BabaAdi { get; set; }
        public string OrtakNo { get; set; }
        public Nullable<int> SantiyeID { get; set; }
        public Nullable<bool> ToplamBazindaRisk { get; set; }
        public Nullable<decimal> BakiyeLimit { get; set; }
        public Nullable<bool> EfaturaKullanicisi { get; set; }
        public string city2 { get; set; }
        public string town2 { get; set; }
        public string address2 { get; set; }
        public Nullable<int> UstCariID { get; set; }
        public string AltUst { get; set; }
        public Nullable<bool> eFatDuzenlenmesin { get; set; }
        public string NotDefteri { get; set; }
        public string Plaka { get; set; }
        public string PayType { get; set; }
        public Nullable<bool> KomisyonOtomatik { get; set; }
        public Nullable<decimal> FaturaKomisyonGideri { get; set; }
        public string Company_Code { get; set; }
        public string Gsm2 { get; set; }
        public Nullable<int> DepoID { get; set; }
        public Nullable<int> DoktorID { get; set; }
        public string YapilacakIslemler { get; set; }
        public string SeriNo { get; set; }
    }
}
