//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_DETAIL
    {
        public int ID { get; set; }
        public string FirmaAdi { get; set; }
        public string IlgiliKisi { get; set; }
        public string Telefon { get; set; }
        public string Faks { get; set; }
        public string ePosta { get; set; }
        public string WebSite { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
        public string PostaKodu { get; set; }
        public string Adres { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public string MesajNumara { get; set; }
        public string TicaretSicilNo { get; set; }
        public string MersisNo { get; set; }
        public string ServerPaylasim { get; set; }
        public string SicilNo { get; set; }
        public string Ilce { get; set; }
        public string Company_Code { get; set; }
    }
}
