//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENCY_LIST
    {
        public int ID { get; set; }
        public string ParaBirimiN { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<bool> Durumu { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public string Company_Code { get; set; }
    }
}
