//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dekont
    {
        public int ID { get; set; }
        public string IslemTipi { get; set; }
        public string IslemNo { get; set; }
        public string IslemTarih { get; set; }
        public Nullable<int> CariID { get; set; }
        public Nullable<int> crMKodID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> MuhKodID { get; set; }
        public string Aciklama { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string KayT { get; set; }
        public string DegT { get; set; }
        public string Donem { get; set; }
        public Nullable<int> KayitPersonelID { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<int> OzelKodID { get; set; }
        public Nullable<System.DateTime> VadeTarihi { get; set; }
        public Nullable<decimal> Kur { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public Nullable<int> SantiyeID { get; set; }
        public Nullable<int> DoktorID { get; set; }
        public string Company_Code { get; set; }
        public Nullable<decimal> TLUSDKUR { get; set; }
        public Nullable<decimal> TLEURKUR { get; set; }
        public string KONTRATNO { get; set; }
        public string IHRPOZ { get; set; }
        public string ITLPOZ { get; set; }
        public string AracPlaka { get; set; }
        public string Plaka2 { get; set; }
    }
}
