//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRaysa
    {
        public int EmployeeRaysaID { get; set; }
        public Nullable<int> PozisyonNo { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriIlgili { get; set; }
        public string MusteriReferans { get; set; }
        public string SozlesmeNo { get; set; }
        public string CikisUlke { get; set; }
        public string CikisSehir { get; set; }
        public string CikisAdres { get; set; }
        public string VarisUlke { get; set; }
        public string VarisSehir { get; set; }
        public string VarisAdres { get; set; }
        public string KaraHava { get; set; }
        public string AracTip { get; set; }
        public string PlakaCekici { get; set; }
        public string TirKarneNo { get; set; }
        public string SoforAdSoyad { get; set; }
        public string AracFirma { get; set; }
        public string TransferFirma { get; set; }
        public string PlakaDorse { get; set; }
        public Nullable<bool> Cmr { get; set; }
        public Nullable<bool> T1 { get; set; }
        public Nullable<bool> T2 { get; set; }
        public Nullable<bool> Pasaport { get; set; }
        public Nullable<bool> SurucuPasaport { get; set; }
        public Nullable<int> YuklemeID { get; set; }
        public Nullable<int> BosaltmaID { get; set; }
        public Nullable<int> FaturaID { get; set; }
        public string Aciklama { get; set; }
        public string Guzergah { get; set; }
        public Nullable<System.DateTime> GTarih { get; set; }
        public string Dozvala { get; set; }
        public Nullable<decimal> AvansTurkiye { get; set; }
        public Nullable<decimal> AvansYurtDisi { get; set; }
        public Nullable<decimal> Gemi { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
        public string Gumrukleme { get; set; }
        public string Yil { get; set; }
        public string Ay { get; set; }
        public Nullable<decimal> SatisNavlun { get; set; }
        public string AySayi { get; set; }
        public string Renk { get; set; }
        public Nullable<System.DateTime> YuklemeTarihi { get; set; }
        public Nullable<System.DateTime> BosaltmaTarihi { get; set; }
        public string KontratNo { get; set; }
        public string YAck1 { get; set; }
        public string YCins1 { get; set; }
        public Nullable<decimal> YKap1 { get; set; }
        public Nullable<System.DateTime> YTarih1 { get; set; }
        public Nullable<decimal> YTonKg1 { get; set; }
        public string YGumruk1 { get; set; }
        public Nullable<System.DateTime> YGumrukTarih1 { get; set; }
        public string YSinirKapisi1 { get; set; }
        public string YAck2 { get; set; }
        public string YCins2 { get; set; }
        public Nullable<decimal> YKap2 { get; set; }
        public Nullable<System.DateTime> YTarih2 { get; set; }
        public Nullable<decimal> YTonKg2 { get; set; }
        public string YGumruk2 { get; set; }
        public Nullable<System.DateTime> YGumrukTarih2 { get; set; }
        public string YSinirKapisi2 { get; set; }
        public string BAck2 { get; set; }
        public string BCins2 { get; set; }
        public Nullable<decimal> BKap2 { get; set; }
        public Nullable<System.DateTime> BTarih2 { get; set; }
        public Nullable<decimal> BTonKg2 { get; set; }
        public string BGumruk2 { get; set; }
        public Nullable<System.DateTime> BGumrukTarih2 { get; set; }
        public string BSinirKapisi2 { get; set; }
        public string BAck1 { get; set; }
        public string BCins1 { get; set; }
        public Nullable<decimal> BKap1 { get; set; }
        public Nullable<System.DateTime> BTarih1 { get; set; }
        public Nullable<decimal> BTonKg1 { get; set; }
        public string BGumruk1 { get; set; }
        public Nullable<System.DateTime> BGumrukTarih1 { get; set; }
        public string BSinirKapisi1 { get; set; }
        public string FAck1 { get; set; }
        public Nullable<decimal> FBakiye1 { get; set; }
        public Nullable<decimal> FNavlun1 { get; set; }
        public string FPesinat1 { get; set; }
        public Nullable<System.DateTime> FTarihNo1 { get; set; }
        public string FAck2 { get; set; }
        public Nullable<decimal> FBakiye2 { get; set; }
        public Nullable<decimal> FNavlun2 { get; set; }
        public string FPesinat2 { get; set; }
        public Nullable<System.DateTime> FTarihNo2 { get; set; }
        public string AracSeferTipi { get; set; }
        public Nullable<bool> Forwarder { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<decimal> CikisiYakitLT { get; set; }
        public Nullable<decimal> KapidanAlinantLT { get; set; }
        public Nullable<decimal> CikisTL { get; set; }
        public Nullable<decimal> CikisiYakitKM { get; set; }
        public Nullable<decimal> CikisEUR { get; set; }
        public Nullable<bool> Ithalat { get; set; }
        public string TasimaTipi { get; set; }
        public Nullable<decimal> Avans1 { get; set; }
        public Nullable<decimal> Avans2 { get; set; }
        public Nullable<decimal> Avans3 { get; set; }
        public Nullable<decimal> Avans4 { get; set; }
        public Nullable<decimal> Avans5 { get; set; }
        public string AvansAck1 { get; set; }
        public string AvansAck2 { get; set; }
        public string AvansAck3 { get; set; }
        public string AvansAck4 { get; set; }
        public string AvansAck5 { get; set; }
        public Nullable<decimal> ToplamAvans { get; set; }
        public string Ulasim { get; set; }
        public Nullable<decimal> VarisKm { get; set; }
        public string AvansPB1 { get; set; }
        public string AvansPB2 { get; set; }
        public string AvansPB3 { get; set; }
        public string AvansPB4 { get; set; }
        public string AvansPB5 { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public string MusteriOrder { get; set; }
        public string YAdres1 { get; set; }
        public string YAdres2 { get; set; }
        public string BAdres1 { get; set; }
        public string BAdres2 { get; set; }
        public string PBNavlun2 { get; set; }
        public Nullable<decimal> ToplamNavlunEUR { get; set; }
        public Nullable<bool> TasimaSozlesme { get; set; }
    }
}
