//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        public int ID { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaEMail { get; set; }
        public string FirmaSifre { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public string Company_Code { get; set; }
        public string FirmaTel { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<bool> Demo { get; set; }
    }
}
