//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public int ID { get; set; }
        public string Durumu { get; set; }
        public string kdvDH { get; set; }
        public string KapaliAcik { get; set; }
        public string VadeKontrol { get; set; }
        public string IrsaliyeID { get; set; }
        public Nullable<int> AktarilanFID { get; set; }
        public string FaturaType { get; set; }
        public string fType { get; set; }
        public string FaturaNo { get; set; }
        public string FaturaTarihi { get; set; }
        public string paraBirimi { get; set; }
        public Nullable<int> CariID { get; set; }
        public string CariKodu { get; set; }
        public string CariUnvan { get; set; }
        public string CariVergD { get; set; }
        public string CariVergiNo { get; set; }
        public Nullable<int> personelID { get; set; }
        public string Aciklama { get; set; }
        public string gVadeTarih { get; set; }
        public Nullable<decimal> gKDV { get; set; }
        public Nullable<decimal> g18KDV { get; set; }
        public Nullable<decimal> g8KDV { get; set; }
        public Nullable<decimal> g1KDV { get; set; }
        public Nullable<decimal> gTevfikat { get; set; }
        public string gIadeSuresi { get; set; }
        public Nullable<decimal> brutToplam { get; set; }
        public Nullable<decimal> satirIskonta { get; set; }
        public Nullable<decimal> ozelIskonta { get; set; }
        public Nullable<decimal> toplamIskonta { get; set; }
        public Nullable<decimal> netToplam { get; set; }
        public Nullable<decimal> tKDV { get; set; }
        public Nullable<decimal> tTevfikat { get; set; }
        public Nullable<decimal> genelToplam { get; set; }
        public string KayitT { get; set; }
        public string DegT { get; set; }
        public Nullable<decimal> FKuru { get; set; }
        public Nullable<decimal> YerelTutar { get; set; }
        public string Saat { get; set; }
        public string Donem { get; set; }
        public string Aciklama2 { get; set; }
        public string YazdirmaDurumu { get; set; }
        public Nullable<int> ServisCihazID { get; set; }
        public string VadeGun { get; set; }
        public string PrimYuzde { get; set; }
        public Nullable<decimal> DolarKur { get; set; }
        public Nullable<decimal> EuroKur { get; set; }
        public Nullable<int> FaturaOzelKod { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public string IrsaliyeTuru { get; set; }
        public Nullable<int> KayitPersonelID { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public string FaturaSeri { get; set; }
        public string OzelAlan1 { get; set; }
        public string OzelAlan2 { get; set; }
        public string OzelAlan3 { get; set; }
        public string OzelAlan4 { get; set; }
        public string OzelAlan5 { get; set; }
        public string FaturaAdresi { get; set; }
        public string Yetkili { get; set; }
        public string SevkAdresi { get; set; }
        public Nullable<System.DateTime> SevkTarihi { get; set; }
        public string FatTip { get; set; }
        public Nullable<decimal> tOIV { get; set; }
        public Nullable<System.DateTime> ipTalTarihi { get; set; }
        public Nullable<System.DateTime> KontrolTarih { get; set; }
        public Nullable<int> AdresID { get; set; }
        public Nullable<decimal> gIskonta { get; set; }
        public string TevkifatTur { get; set; }
        public string SeriNoList { get; set; }
        public Nullable<decimal> tmaliyet { get; set; }
        public string OzelAlan6 { get; set; }
        public string OzelAlan7 { get; set; }
        public string OzelAlan8 { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public Nullable<bool> CariyeIslesin { get; set; }
        public Nullable<bool> EBelgeGonderimi { get; set; }
        public Nullable<decimal> FaturaOdemesi { get; set; }
        public Nullable<decimal> GbpKur { get; set; }
        public Nullable<decimal> ChfKur { get; set; }
        public Nullable<decimal> OTVToplami { get; set; }
        public Nullable<bool> MiktarBasinaOTVDurumu { get; set; }
        public Nullable<int> AracID { get; set; }
        public Nullable<int> SantiyeID { get; set; }
        public Nullable<bool> DolarVar { get; set; }
        public Nullable<bool> EuroVar { get; set; }
        public Nullable<bool> GBPVar { get; set; }
        public string CMR { get; set; }
        public Nullable<bool> T1 { get; set; }
        public Nullable<bool> T2 { get; set; }
        public Nullable<bool> FaturaYuklendi { get; set; }
        public Nullable<bool> Pasaport { get; set; }
        public Nullable<bool> EmanetIrsaliyesi { get; set; }
        public Nullable<decimal> g10KDV { get; set; }
        public Nullable<decimal> MKDkur { get; set; }
        public string Plaka1 { get; set; }
        public string Plaka2 { get; set; }
        public Nullable<bool> eFatDuz { get; set; }
        public Nullable<decimal> YerelTL { get; set; }
        public string OB_FaturaDurumu { get; set; }
        public string OB_UUID { get; set; }
        public Nullable<decimal> jpykur { get; set; }
        public Nullable<decimal> TLjpyKur { get; set; }
        public Nullable<decimal> HAFKomisyon { get; set; }
        public Nullable<int> USTFATID { get; set; }
        public string HAFID { get; set; }
        public Nullable<decimal> ManuelFarkKur { get; set; }
        public Nullable<decimal> g19KDV { get; set; }
        public Nullable<bool> KdvliKomisyon { get; set; }
        public Nullable<decimal> TLUSDKUR { get; set; }
        public Nullable<decimal> TLEURKUR { get; set; }
        public Nullable<decimal> TLGBPKUR { get; set; }
        public string Company_Code { get; set; }
        public Nullable<int> DoktorID { get; set; }
        public Nullable<bool> Belgesiz { get; set; }
    }
}
