//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_DETAIL
    {
        public int ID { get; set; }
        public string Durumu { get; set; }
        public Nullable<int> faturaID { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string IslemTuru { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> depoID { get; set; }
        public Nullable<int> personelID { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<decimal> actTutar { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string Birim { get; set; }
        public string VadeTarih { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<decimal> Iskonta { get; set; }
        public Nullable<decimal> Iskonta2 { get; set; }
        public Nullable<decimal> Iskonta3 { get; set; }
        public Nullable<decimal> Iskonta4 { get; set; }
        public Nullable<decimal> Iskonta5 { get; set; }
        public Nullable<int> Tevfikat { get; set; }
        public string IadeSuresi { get; set; }
        public string SeriNo { get; set; }
        public string pBirimi { get; set; }
        public string Variyant { get; set; }
        public string VariyantSel { get; set; }
        public Nullable<decimal> Kur { get; set; }
        public Nullable<decimal> Maliyet { get; set; }
        public string Donem { get; set; }
        public Nullable<int> GarantiSuresi { get; set; }
        public string FaturaMaliyeti { get; set; }
        public Nullable<int> CihazID { get; set; }
        public string EkAciklama { get; set; }
        public Nullable<int> SatirOzelKodID { get; set; }
        public string Fparabirimi { get; set; }
        public Nullable<decimal> BirimAdet { get; set; }
        public Nullable<decimal> AdetFiyati { get; set; }
        public Nullable<bool> IrsaliyedenGecis { get; set; }
        public Nullable<decimal> gBirimMiktar { get; set; }
        public Nullable<decimal> YerelNet { get; set; }
        public Nullable<decimal> mf { get; set; }
        public Nullable<bool> FiyatGuncelle { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<System.DateTime> HizmetSonlanma { get; set; }
        public Nullable<int> OIV { get; set; }
        public Nullable<System.DateTime> KontrolTarih { get; set; }
        public Nullable<decimal> frtFiyat { get; set; }
        public Nullable<decimal> ftrSonDesc { get; set; }
        public string SeriNoList { get; set; }
        public Nullable<decimal> OTV { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<int> SiparisSatirID { get; set; }
        public Nullable<decimal> MetreMiktarAdet { get; set; }
        public Nullable<decimal> Uzunluk { get; set; }
        public Nullable<decimal> Genislik { get; set; }
        public Nullable<decimal> Derinlik { get; set; }
        public Nullable<int> TedCariID { get; set; }
        public Nullable<decimal> MiktarBasinaOTV { get; set; }
        public Nullable<decimal> FireMiktar { get; set; }
        public Nullable<int> TakimID { get; set; }
        public string UrunSeriNoMob { get; set; }
        public string RayRefNo { get; set; }
        public string RayOrderNo { get; set; }
        public string RayKontratNo { get; set; }
        public string RaySofor { get; set; }
        public string MalzemeSayi { get; set; }
        public Nullable<decimal> SevkMiktar { get; set; }
        public Nullable<decimal> IadeMiktar { get; set; }
        public string IHRPOZ { get; set; }
        public string ITLPOZ { get; set; }
        public string UnicodeSF { get; set; }
        public Nullable<int> KAMHAFID { get; set; }
        public string STAciklama2 { get; set; }
        public Nullable<bool> AracGiderIslemesin { get; set; }
        public string Motor { get; set; }
        public string MotorSN { get; set; }
        public string GUCK { get; set; }
        public string GUCKSN { get; set; }
        public string Alici { get; set; }
        public string AliciSN { get; set; }
        public string Kumanda { get; set; }
        public string KumandaSN { get; set; }
        public string AracPlaka2 { get; set; }
        public Nullable<decimal> kpGenislik { get; set; }
        public Nullable<decimal> KPYukseklik { get; set; }
        public Nullable<decimal> KPIskonto { get; set; }
        public Nullable<decimal> KpKar { get; set; }
        public string AracPlaka { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public string Company_Code { get; set; }
        public Nullable<decimal> AlisF { get; set; }
        public string Birim2 { get; set; }
        public Nullable<decimal> Miktar2 { get; set; }
        public Nullable<decimal> AdetMetre { get; set; }
        public Nullable<decimal> KarotDerinlik { get; set; }
    }
}
