//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDVRaporuTL
    {
        public string Donem { get; set; }
        public Nullable<decimal> Sat__Tutar { get; set; }
        public Nullable<decimal> Sat__KDV_Tutar { get; set; }
        public Nullable<decimal> Al__Tutar { get; set; }
        public Nullable<decimal> Al__KDV_Tutar { get; set; }
        public Nullable<decimal> KDV_Fark { get; set; }
        public Nullable<decimal> Sat___18_KDV_Tutar { get; set; }
        public Nullable<decimal> Sat___8_KDV_Tutar { get; set; }
        public Nullable<decimal> Sat___1_KDV_Tutar { get; set; }
        public Nullable<decimal> Sat___19_KDV_Tutar { get; set; }
        public Nullable<decimal> Al___18_KDV_Tutar { get; set; }
        public Nullable<decimal> Al___8_KDV_Tutar { get; set; }
        public Nullable<decimal> Al___1_KDV_Tutar { get; set; }
        public Nullable<decimal> Al___19_KDV_Tutar { get; set; }
    }
}
