//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOD_BALANCE
    {
        public int ID { get; set; }
        public Nullable<int> ozelKodID { get; set; }
        public string paraBirimi { get; set; }
        public Nullable<decimal> bakiye { get; set; }
        public Nullable<decimal> Borc { get; set; }
        public Nullable<decimal> Alacak { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public string Company_Code { get; set; }
    }
}
