//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFER
    {
        public int ID { get; set; }
        public string TeklifNo { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public Nullable<System.DateTime> TeklifSonTarihi { get; set; }
        public Nullable<int> CariID { get; set; }
        public Nullable<decimal> BrutToplam { get; set; }
        public Nullable<decimal> NetToplam { get; set; }
        public Nullable<decimal> ToplamKdv { get; set; }
        public Nullable<decimal> ToplamIskonto { get; set; }
        public Nullable<decimal> GenelToplam { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string kdvDH { get; set; }
        public string ParaBirimi { get; set; }
        public string Aciklama { get; set; }
        public string Donem { get; set; }
        public Nullable<decimal> q18Kdv { get; set; }
        public Nullable<decimal> q8Kdv { get; set; }
        public Nullable<decimal> q1Kdv { get; set; }
        public Nullable<decimal> Iskonto { get; set; }
        public string Durumu { get; set; }
        public string IslemTipi { get; set; }
        public Nullable<decimal> OzelIskonto { get; set; }
        public Nullable<decimal> SatirIskonto { get; set; }
        public string SozlesmeMetni { get; set; }
        public Nullable<int> OzelKodID { get; set; }
        public Nullable<decimal> YerelTutar { get; set; }
        public Nullable<decimal> DolarKur { get; set; }
        public Nullable<decimal> EuroKur { get; set; }
        public Nullable<int> KayitPersonelID { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<decimal> Kur { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public string OzelAlan1 { get; set; }
        public string OzelAlan2 { get; set; }
        public string OzelAlan3 { get; set; }
        public string OzelAlan4 { get; set; }
        public string OzelAlan5 { get; set; }
        public Nullable<bool> IptalEdildi { get; set; }
        public Nullable<System.DateTime> VadeTarihi { get; set; }
        public Nullable<decimal> tOIV { get; set; }
        public Nullable<decimal> tOTV { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public Nullable<decimal> ChfKur { get; set; }
        public Nullable<decimal> GbpKur { get; set; }
        public string TekTip { get; set; }
        public string Ack1 { get; set; }
        public Nullable<bool> Aktarildi { get; set; }
        public Nullable<bool> UrunAciklamasiGoster { get; set; }
        public string TOdemeSekli { get; set; }
        public string TeklifSuresi { get; set; }
        public string Teslimat { get; set; }
        public string Company_Code { get; set; }
        public Nullable<System.DateTime> TeklifTeslimTarihi { get; set; }
    }
}
