//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS_DETAIL
    {
        public int ID { get; set; }
        public string Durumu { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string IslemTuru { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> depoID { get; set; }
        public Nullable<int> personelID { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<decimal> actTutar { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string Birim { get; set; }
        public string VadeTarih { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<decimal> Iskonta { get; set; }
        public Nullable<decimal> Iskonta2 { get; set; }
        public Nullable<decimal> Iskonta3 { get; set; }
        public Nullable<decimal> Iskonta4 { get; set; }
        public Nullable<decimal> Iskonta5 { get; set; }
        public Nullable<int> Tevfikat { get; set; }
        public string IadeSuresi { get; set; }
        public string SeriNo { get; set; }
        public string pBirimi { get; set; }
        public string Variyant { get; set; }
        public string VariyantSel { get; set; }
        public Nullable<decimal> Kur { get; set; }
        public Nullable<decimal> Maliyet { get; set; }
        public string Donem { get; set; }
        public Nullable<int> GarantiSuresi { get; set; }
        public string FaturaMaliyeti { get; set; }
        public Nullable<int> CihazID { get; set; }
        public string EkAciklama { get; set; }
        public Nullable<int> SatirOzelKodID { get; set; }
        public string Fparabirimi { get; set; }
        public Nullable<decimal> BirimAdet { get; set; }
        public Nullable<decimal> AdetFiyati { get; set; }
        public Nullable<bool> IrsaliyedenGecis { get; set; }
        public Nullable<decimal> gBirimMiktar { get; set; }
        public Nullable<decimal> YerelNet { get; set; }
        public Nullable<decimal> mf { get; set; }
        public Nullable<bool> FiyatGuncelle { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<System.DateTime> HizmetSonlanma { get; set; }
        public Nullable<int> OIV { get; set; }
        public Nullable<System.DateTime> KontrolTarih { get; set; }
        public Nullable<decimal> frtFiyat { get; set; }
        public Nullable<decimal> ftrSonDesc { get; set; }
        public string SeriNoList { get; set; }
        public Nullable<decimal> OTV { get; set; }
        public Nullable<int> TeklifID { get; set; }
        public Nullable<decimal> KalanMiktar { get; set; }
        public Nullable<int> TeklifSatirID { get; set; }
        public Nullable<decimal> UretimMiktari { get; set; }
        public Nullable<decimal> Derinlik { get; set; }
        public Nullable<decimal> MetreMiktarAdet { get; set; }
        public Nullable<decimal> Uzunluk { get; set; }
        public Nullable<decimal> Genislik { get; set; }
        public Nullable<decimal> MiktarBasinaOTV { get; set; }
        public string SipSeriNo { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public string Company_Code { get; set; }
    }
}
