//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYROLL_CS
    {
        public int ID { get; set; }
        public Nullable<int> BordroID { get; set; }
        public string CariUnvan { get; set; }
        public Nullable<int> CariID { get; set; }
        public Nullable<int> BorcluAlacakli { get; set; }
        public string PortfoyNo { get; set; }
        public string IslemTipi { get; set; }
        public string BordroTipi { get; set; }
        public string SeriNo { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public Nullable<System.DateTime> evrakGT { get; set; }
        public Nullable<System.DateTime> VadeTarih { get; set; }
        public string Durumu { get; set; }
        public string Aciklama { get; set; }
        public string BankaAdi { get; set; }
        public string SubeAdi { get; set; }
        public string OdemeYeri { get; set; }
        public string KesideciUnvan { get; set; }
        public string KesideciTel { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string Donem { get; set; }
        public string RiskLimitKapsam { get; set; }
        public Nullable<int> ZimmetPersonelID { get; set; }
        public string ZimmetAciklama { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> KayitPersonelID { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public Nullable<int> OzelKodID { get; set; }
        public Nullable<decimal> TahsilEdilen { get; set; }
        public string Ciro { get; set; }
        public Nullable<int> BankaID { get; set; }
        public string CekBankaHesapNo { get; set; }
        public Nullable<bool> HizliSatistan { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public Nullable<decimal> PrimOr { get; set; }
        public Nullable<int> SantiyeID { get; set; }
        public string Company_Code { get; set; }
    }
}
