//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYROLL
    {
        public int ID { get; set; }
        public string IslemTipi { get; set; }
        public string IslemNo { get; set; }
        public Nullable<System.DateTime> IslemTarih { get; set; }
        public Nullable<int> CariID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> VadeFarki { get; set; }
        public Nullable<System.DateTime> OrtalamaVade { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<int> KasaBankaID { get; set; }
        public string Donem { get; set; }
        public Nullable<int> KayitPersonelID { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<decimal> Kur { get; set; }
        public Nullable<int> OzelKodID { get; set; }
        public string Durumu { get; set; }
        public Nullable<int> BankaIDGC { get; set; }
        public Nullable<int> KasaIDOT { get; set; }
        public Nullable<int> BankaIDOT { get; set; }
        public Nullable<int> FaktoringTahsilatID { get; set; }
        public Nullable<int> FaktoringTediyeID { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public Nullable<int> AdresID { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public Nullable<decimal> PrimOr { get; set; }
        public Nullable<int> SantiyeID { get; set; }
        public string IslemCODE { get; set; }
        public string Company_Code { get; set; }
        public string EvrakType { get; set; }
    }
}
