//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string BabaAdi { get; set; }
        public Nullable<decimal> Maasi { get; set; }
        public string Pozisyonu { get; set; }
        public string TCNo { get; set; }
        public string Egitimi { get; set; }
        public string Milleti { get; set; }
        public string DogumT { get; set; }
        public string MedeniH { get; set; }
        public string Cinsiyet { get; set; }
        public string IL { get; set; }
        public string Ilce { get; set; }
        public string Adres { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string EPosta { get; set; }
        public string PostaKodu { get; set; }
        public string EkBilgiler { get; set; }
        public string Fotograf { get; set; }
        public string cSaatleri1 { get; set; }
        public string cSaatleri2 { get; set; }
        public string cGunleri { get; set; }
        public string Sifre { get; set; }
        public string KayitT { get; set; }
        public string SonDT { get; set; }
        public string PrimYuzde { get; set; }
        public Nullable<int> MaasGunu { get; set; }
        public string ComputerName { get; set; }
        public Nullable<bool> BHatirla { get; set; }
        public Nullable<decimal> Alacak { get; set; }
        public Nullable<decimal> Borc { get; set; }
        public Nullable<System.DateTime> IseBaslama { get; set; }
        public Nullable<System.DateTime> IstenCikis { get; set; }
        public string PersonelNo { get; set; }
        public string PersonelGrubu { get; set; }
        public string PB { get; set; }
        public string OturumAdi { get; set; }
        public Nullable<int> vKasaID { get; set; }
        public Nullable<int> vBankaID { get; set; }
        public Nullable<int> vKKTID { get; set; }
        public Nullable<int> vDepoID { get; set; }
        public string YazdirSec { get; set; }
        public Nullable<bool> Giris { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public Nullable<int> MerkezID { get; set; }
        public string CalismaDurumu { get; set; }
        public string SatisPerSec { get; set; }
        public string MailSifre { get; set; }
        public string KadroSekli { get; set; }
        public string PersonelBolumu { get; set; }
        public Nullable<int> SenelikIzin { get; set; }
        public string Zimmettekiler { get; set; }
        public string SicilNo { get; set; }
        public Nullable<System.DateTime> ProSonGirisTarihi { get; set; }
        public string WebKA { get; set; }
        public string WebSifre { get; set; }
        public string IBAN2 { get; set; }
        public string IBAN3 { get; set; }
        public string IBAN4 { get; set; }
        public string IBAN5 { get; set; }
        public string Banka5 { get; set; }
        public string Banka4 { get; set; }
        public string Banka3 { get; set; }
        public string Banka2 { get; set; }
        public string Banka1 { get; set; }
        public string IBAN { get; set; }
        public Nullable<System.DateTime> PasaportBaslangic { get; set; }
        public Nullable<System.DateTime> PasaportBitis { get; set; }
        public Nullable<System.DateTime> VizeBaslangic { get; set; }
        public Nullable<System.DateTime> VizeBitis { get; set; }
        public string VizeTuru { get; set; }
        public string PlakaArac { get; set; }
        public string YeniGrup { get; set; }
        public string IRSoneki { get; set; }
        public string SubeKodu { get; set; }
        public Nullable<int> PerakendeIslemEkraniEn { get; set; }
        public Nullable<int> PerakendeYanyanaUrun { get; set; }
        public Nullable<decimal> AlacakEUR { get; set; }
        public Nullable<decimal> BORCEUR { get; set; }
        public string KDurum { get; set; }
        public string NotDefteri { get; set; }
        public string FatOneki { get; set; }
        public string ArsOneki { get; set; }
        public string Company_Code { get; set; }
        public string GecmisOneki { get; set; }
        public Nullable<int> ToplamAdet { get; set; }
        public Nullable<int> sCariID { get; set; }
        public byte[] PersonelBase64 { get; set; }
        public string GecmisArvOneki { get; set; }
    }
}
