//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_HAREKET
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string FaturaNo { get; set; }
        public string IslemTuru { get; set; }
        public string Durumu { get; set; }
        public Nullable<decimal> gBirimMiktar { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> depoID { get; set; }
        public Nullable<int> GdepoID { get; set; }
        public Nullable<int> personelID { get; set; }
        public Nullable<decimal> YerelBrut { get; set; }
        public int cikan { get; set; }
        public Nullable<decimal> MF { get; set; }
        public string GC { get; set; }
        public Nullable<decimal> YerelNet { get; set; }
        public Nullable<int> CariID { get; set; }
        public int hammaliyet { get; set; }
        public Nullable<decimal> MaliyetBrut { get; set; }
        public Nullable<decimal> MaliyetNet { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public string FaturaParaBirimi { get; set; }
        public string SatirParaBirimi { get; set; }
        public Nullable<decimal> DövizliFiyatBrut { get; set; }
        public Nullable<decimal> Iskonta2 { get; set; }
        public Nullable<decimal> Iskonta3 { get; set; }
        public Nullable<decimal> Iskonta4 { get; set; }
        public Nullable<decimal> Iskonta5 { get; set; }
        public string EkAciklama { get; set; }
        public string SeriNo { get; set; }
        public string Variyant { get; set; }
        public Nullable<int> VariyantSel { get; set; }
        public string Donem { get; set; }
        public Nullable<int> SatirOzelKodID { get; set; }
        public Nullable<int> GarantiSuresi { get; set; }
        public string StokKodu { get; set; }
        public string UrunAdi { get; set; }
        public string Marka { get; set; }
        public string Grubu { get; set; }
        public string Barkod { get; set; }
        public Nullable<int> SKDV { get; set; }
        public Nullable<decimal> SatishFiyat { get; set; }
        public string Birimi { get; set; }
        public Nullable<decimal> AlishFiyat { get; set; }
        public string UrunTuru { get; set; }
        public Nullable<bool> StokList { get; set; }
        public Nullable<int> RafOmru { get; set; }
        public Nullable<decimal> Sonalis { get; set; }
        public string satirACk { get; set; }
        public Nullable<int> TedCariID { get; set; }
        public string TABLO { get; set; }
        public Nullable<int> TakimSipID { get; set; }
        public Nullable<int> TakimID { get; set; }
        public Nullable<decimal> AlisF { get; set; }
        public string Kategori1 { get; set; }
        public string Kategori2 { get; set; }
        public Nullable<int> DoktorID { get; set; }
        public Nullable<int> FirmaID { get; set; }
    }
}
