//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETAIL_DETAIL
    {
        public int ID { get; set; }
        public Nullable<int> SatisID { get; set; }
        public Nullable<int> StokID { get; set; }
        public Nullable<int> DepoID { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public string Birim { get; set; }
        public string SeriNo { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<int> VariyantID { get; set; }
        public Nullable<decimal> Kur { get; set; }
        public string Donem { get; set; }
        public Nullable<int> GarantiSuresi { get; set; }
        public Nullable<decimal> Maliyet { get; set; }
        public string FaturaMaliyeti { get; set; }
        public string IadeSuresi { get; set; }
        public string VadeTarihi { get; set; }
        public Nullable<int> SatirOzelKodID { get; set; }
        public string IslemTipi { get; set; }
        public Nullable<decimal> BirimAdet { get; set; }
        public Nullable<decimal> gBirimMiktar { get; set; }
        public string SatisPB { get; set; }
        public Nullable<int> EkOzellikID { get; set; }
        public Nullable<decimal> Iskonto2 { get; set; }
        public Nullable<decimal> Iskonto3 { get; set; }
        public Nullable<decimal> Iskonto4 { get; set; }
        public Nullable<decimal> Iskonto5 { get; set; }
        public Nullable<decimal> Uzunluk { get; set; }
        public Nullable<decimal> Genislik { get; set; }
        public Nullable<decimal> MetreMiktarAdet { get; set; }
        public Nullable<decimal> Derinlik { get; set; }
        public Nullable<decimal> PrimYuzdesi { get; set; }
        public Nullable<decimal> MiktarBasinaOTV { get; set; }
        public Nullable<System.DateTime> SatisTarihi { get; set; }
        public Nullable<int> SatisCariID { get; set; }
        public string SatisNo { get; set; }
        public Nullable<decimal> RIskonto { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public string Company_Code { get; set; }
        public Nullable<decimal> AlisF { get; set; }
    }
}
