//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETAIL
    {
        public int ID { get; set; }
        public string Durum { get; set; }
        public string IslemNo { get; set; }
        public string IslemTipi { get; set; }
        public Nullable<System.DateTime> IslemTarih { get; set; }
        public Nullable<int> CariID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> ntoID { get; set; }
        public Nullable<decimal> ntoTutar { get; set; }
        public Nullable<int> KasaID { get; set; }
        public Nullable<int> kktID { get; set; }
        public Nullable<decimal> kktTutar { get; set; }
        public Nullable<int> BankaID { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<decimal> BrutTutar { get; set; }
        public Nullable<decimal> KDVTutar { get; set; }
        public Nullable<decimal> Indirim { get; set; }
        public Nullable<decimal> GenelTutar { get; set; }
        public string Aciklama { get; set; }
        public string AcikKapali { get; set; }
        public Nullable<System.DateTime> KayT { get; set; }
        public Nullable<System.DateTime> DegT { get; set; }
        public string IslemTipiHP { get; set; }
        public string Donem { get; set; }
        public string PersonelYuzde { get; set; }
        public Nullable<decimal> NetTutar { get; set; }
        public Nullable<decimal> ParaUstu { get; set; }
        public Nullable<int> IndirimID { get; set; }
        public string BonusKartID { get; set; }
        public Nullable<decimal> BonusKartTutar { get; set; }
        public string gIadeSuresi { get; set; }
        public string gVadeTarihi { get; set; }
        public Nullable<int> PerakendeOzelKod { get; set; }
        public Nullable<System.DateTime> IadeTarih { get; set; }
        public Nullable<int> SatisIadeID { get; set; }
        public Nullable<int> KayitPersonelID { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<decimal> Kur { get; set; }
        public Nullable<int> ParaKartTahsilatID { get; set; }
        public Nullable<decimal> ParaKartTahsilatTutar { get; set; }
        public Nullable<System.DateTime> VadeT { get; set; }
        public string KdvDH { get; set; }
        public Nullable<decimal> Iskonto { get; set; }
        public Nullable<decimal> tmaliyet { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public Nullable<decimal> PerakendeOdemesi { get; set; }
        public Nullable<decimal> PrimTutari { get; set; }
        public Nullable<decimal> SgkTutar { get; set; }
        public Nullable<decimal> KalanTutar { get; set; }
        public Nullable<decimal> TahsilEdilenTutar { get; set; }
        public Nullable<decimal> hvlTutar { get; set; }
        public Nullable<int> hvlID { get; set; }
        public string SatisNo { get; set; }
        public Nullable<decimal> TaksitTutar { get; set; }
        public Nullable<decimal> ToplamIsk { get; set; }
        public Nullable<decimal> OzelIsk { get; set; }
        public Nullable<decimal> SatirIsk { get; set; }
        public Nullable<int> MONEY_ID { get; set; }
        public Nullable<decimal> MONEY_ORAN { get; set; }
        public Nullable<int> SatilanPErsonelID { get; set; }
        public string Company_Code { get; set; }
    }
}
