//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARYPERSON
    {
        public int ID { get; set; }
        public string IslemTipi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string IslemNo { get; set; }
        public Nullable<int> kasaID { get; set; }
        public Nullable<int> bankaID { get; set; }
        public Nullable<int> krediKID { get; set; }
        public string Donem { get; set; }
        public Nullable<int> Personel { get; set; }
        public Nullable<int> OdenenPersonel { get; set; }
        public string ParaBirimi { get; set; }
        public string AlacakBorcTipi { get; set; }
        public Nullable<int> FisID { get; set; }
        public Nullable<int> TekrarlananID { get; set; }
        public Nullable<int> OzelKodID { get; set; }
        public Nullable<int> KayitPersonelID { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.DateTime> VadeTarihi { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public Nullable<bool> PersonelBakiyesineIslemesin { get; set; }
        public Nullable<decimal> TLUSDKUR { get; set; }
        public string Plaka2 { get; set; }
        public Nullable<int> SantiyeID { get; set; }
        public string AracPlaka { get; set; }
        public string KontratNo { get; set; }
        public string ITLPozisyonNo { get; set; }
        public string PozisyonNo { get; set; }
        public Nullable<bool> Islemesin { get; set; }
        public Nullable<decimal> kur { get; set; }
        public string Company_Code { get; set; }
        public Nullable<decimal> TLEURKUR { get; set; }
    }
}
