//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sayazilimEntities : DbContext
    {
        public sayazilimEntities()
            : base("name=sayazilimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BALANCE> BALANCE { get; set; }
        public virtual DbSet<CARI_KATEGORI> CARI_KATEGORI { get; set; }
        public virtual DbSet<CASH_PAY> CASH_PAY { get; set; }
        public virtual DbSet<COMPANY_DETAIL> COMPANY_DETAIL { get; set; }
        public virtual DbSet<CURRENCY_LIST> CURRENCY_LIST { get; set; }
        public virtual DbSet<INVOICE_DETAIL> INVOICE_DETAIL { get; set; }
        public virtual DbSet<INVOICE_E> INVOICE_E { get; set; }
        public virtual DbSet<OFFER> OFFER { get; set; }
        public virtual DbSet<OFFER_DETAIL> OFFER_DETAIL { get; set; }
        public virtual DbSet<ORDERS_DETAIL> ORDERS_DETAIL { get; set; }
        public virtual DbSet<OzelKod> OzelKod { get; set; }
        public virtual DbSet<RETAIL> RETAIL { get; set; }
        public virtual DbSet<RETAIL_DETAIL> RETAIL_DETAIL { get; set; }
        public virtual DbSet<SALARYPERSON> SALARYPERSON { get; set; }
        public virtual DbSet<SPECIAL_TECH> SPECIAL_TECH { get; set; }
        public virtual DbSet<STK_KATEGORI> STK_KATEGORI { get; set; }
        public virtual DbSet<Stok> Stok { get; set; }
        public virtual DbSet<TECH_STATE> TECH_STATE { get; set; }
        public virtual DbSet<TECHNICAL_DETAIL> TECHNICAL_DETAIL { get; set; }
        public virtual DbSet<Yetkiler> Yetkiler { get; set; }
        public virtual DbSet<PRODUCT_HAREKET> PRODUCT_HAREKET { get; set; }
        public virtual DbSet<BALANCE_BANK> BALANCE_BANK { get; set; }
        public virtual DbSet<BALANCE_KASA> BALANCE_KASA { get; set; }
        public virtual DbSet<KOD_BALANCE> KOD_BALANCE { get; set; }
        public virtual DbSet<TREE_PRODUCT> TREE_PRODUCT { get; set; }
        public virtual DbSet<PAYROLL> PAYROLL { get; set; }
        public virtual DbSet<PAYROLL_CS> PAYROLL_CS { get; set; }
        public virtual DbSet<PAYROLL_DETAIL_CS> PAYROLL_DETAIL_CS { get; set; }
        public virtual DbSet<Banka> Banka { get; set; }
        public virtual DbSet<Kasa> Kasa { get; set; }
        public virtual DbSet<STORE> STORE { get; set; }
        public virtual DbSet<INVOICE> INVOICE { get; set; }
        public virtual DbSet<ORDERS> ORDERS { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<TECHNICAL_PERIOD> TECHNICAL_PERIOD { get; set; }
        public virtual DbSet<STORE_PROCESS> STORE_PROCESS { get; set; }
        public virtual DbSet<STORE_PROCESS_DETAIL> STORE_PROCESS_DETAIL { get; set; }
        public virtual DbSet<KDVRaporuTL> KDVRaporuTL { get; set; }
        public virtual DbSet<Bedenler> Bedenler { get; set; }
        public virtual DbSet<RENKLER> RENKLER { get; set; }
        public virtual DbSet<Ayarlar> Ayarlar { get; set; }
        public virtual DbSet<VARIANT> VARIANT { get; set; }
        public virtual DbSet<INVOICE_OZEL> INVOICE_OZEL { get; set; }
        public virtual DbSet<Cari> Cari { get; set; }
        public virtual DbSet<TECHNICAL> TECHNICAL { get; set; }
        public virtual DbSet<Dekont> Dekont { get; set; }
        public virtual DbSet<Not_Kategori> Not_Kategori { get; set; }
        public virtual DbSet<Notlar_Listesi> Notlar_Listesi { get; set; }
        public virtual DbSet<COUNTRIES> COUNTRIES { get; set; }
        public virtual DbSet<Firmalar> Firmalar { get; set; }
    }
}
