//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok
    {
        public int ID { get; set; }
        public string StokKodu { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<decimal> StoktaKalan { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<decimal> AlishFiyat { get; set; }
        public string paraBirimiN { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<decimal> SatishFiyat { get; set; }
        public string Barkod { get; set; }
        public string OEM { get; set; }
        public string Kategori { get; set; }
        public string UrunTuru { get; set; }
        public string Marka { get; set; }
        public string GarantiS { get; set; }
        public string Birimi { get; set; }
        public Nullable<decimal> KalanStkU { get; set; }
        public string Durumu { get; set; }
        public string KayitT { get; set; }
        public string DegT { get; set; }
        public string Fotograf { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> PKullan { get; set; }
        public Nullable<bool> StokList { get; set; }
        public string Grubu { get; set; }
        public string Kategori1 { get; set; }
        public string Kategori2 { get; set; }
        public string Kategori3 { get; set; }
        public string Kategori4 { get; set; }
        public string Kategori5 { get; set; }
        public Nullable<decimal> PrimOrani { get; set; }
        public string AlisParaBirimi { get; set; }
        public string AlisParaBirimiN { get; set; }
        public Nullable<int> RafOmru { get; set; }
        public Nullable<decimal> sonAlis { get; set; }
        public Nullable<decimal> sonSatis { get; set; }
        public Nullable<decimal> sonSatisB { get; set; }
        public Nullable<decimal> sonAlisB { get; set; }
        public string PLU { get; set; }
        public Nullable<int> DepartmanID { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public Nullable<int> CafeMID { get; set; }
        public Nullable<decimal> F2 { get; set; }
        public Nullable<decimal> F3 { get; set; }
        public Nullable<decimal> F4 { get; set; }
        public Nullable<decimal> F5 { get; set; }
        public Nullable<decimal> F6 { get; set; }
        public string Detay2 { get; set; }
        public string BRM2 { get; set; }
        public string BRM3 { get; set; }
        public string BRM4 { get; set; }
        public string BRM5 { get; set; }
        public string BRM6 { get; set; }
        public Nullable<bool> WebGorunumu { get; set; }
        public string ENGAciklama { get; set; }
        public Nullable<bool> Aktarildi { get; set; }
        public string ENGUrunAdi { get; set; }
        public string EkAlan { get; set; }
        public Nullable<decimal> MiktarBasinaOTV { get; set; }
        public Nullable<System.DateTime> SonKullanimTarihi { get; set; }
        public string PartiNo { get; set; }
        public string Brkd2 { get; set; }
        public string Brkd3 { get; set; }
        public string Brkd4 { get; set; }
        public string Brkd5 { get; set; }
        public string Brkd6 { get; set; }
        public string KisaKod { get; set; }
        public string AnaKod { get; set; }
        public string Piyasa { get; set; }
        public string UretimYeri { get; set; }
        public string RenkDetay { get; set; }
        public string Kategori7 { get; set; }
        public string Kategori8 { get; set; }
        public string Kategori9 { get; set; }
        public string Kategori10 { get; set; }
        public string Kategori11 { get; set; }
        public Nullable<decimal> kmt7 { get; set; }
        public Nullable<decimal> kmt8 { get; set; }
        public Nullable<decimal> kmt9 { get; set; }
        public Nullable<decimal> kmt10 { get; set; }
        public string Kategori6 { get; set; }
        public Nullable<decimal> kmt1 { get; set; }
        public Nullable<decimal> kmt2 { get; set; }
        public Nullable<decimal> kmt3 { get; set; }
        public Nullable<decimal> kmt4 { get; set; }
        public Nullable<decimal> kmt5 { get; set; }
        public Nullable<decimal> kmt6 { get; set; }
        public Nullable<int> TedarikciID { get; set; }
        public byte[] StokBase64 { get; set; }
        public string FileContentResim { get; set; }
        public string Bilesen { get; set; }
        public Nullable<bool> WebPGoster { get; set; }
        public Nullable<decimal> KoliCarpani { get; set; }
        public string Boyut { get; set; }
        public Nullable<decimal> YeniSiparis { get; set; }
        public Nullable<decimal> Durum { get; set; }
        public Nullable<decimal> Ihtiyac { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
        public Nullable<decimal> Ayrilmis { get; set; }
        public Nullable<decimal> Siparis { get; set; }
        public Nullable<decimal> PIskonto { get; set; }
        public string Fbk2 { get; set; }
        public string Fbk3 { get; set; }
        public string Fbk4 { get; set; }
        public string Fbk5 { get; set; }
        public string Fbk6 { get; set; }
        public string Fbk7 { get; set; }
        public string Fbk8 { get; set; }
        public string Fbk9 { get; set; }
        public string Fbk10 { get; set; }
        public Nullable<decimal> nbadet2 { get; set; }
        public Nullable<decimal> nbadet3 { get; set; }
        public Nullable<decimal> nbadet4 { get; set; }
        public Nullable<decimal> nbadet5 { get; set; }
        public Nullable<decimal> nbadet6 { get; set; }
        public Nullable<decimal> nbadet7 { get; set; }
        public Nullable<decimal> nbadet8 { get; set; }
        public Nullable<decimal> nbadet9 { get; set; }
        public Nullable<decimal> nbadet10 { get; set; }
        public string AgirlikBR { get; set; }
        public Nullable<decimal> BrAgirlik { get; set; }
        public Nullable<decimal> BrAgirlikFiyat { get; set; }
        public Nullable<int> SdepoID { get; set; }
        public Nullable<decimal> GirisTutariBrut { get; set; }
        public Nullable<decimal> GirisTutariNet { get; set; }
        public Nullable<decimal> GirisMiktari { get; set; }
        public Nullable<decimal> CikisTutariBrut { get; set; }
        public Nullable<decimal> CikisTutariNet { get; set; }
        public Nullable<decimal> CikisMiktari { get; set; }
        public Nullable<decimal> DepoMevcudu { get; set; }
        public Nullable<decimal> EnvanterTutari { get; set; }
        public Nullable<decimal> OrtalamaAlisBrut { get; set; }
        public Nullable<decimal> OrtalamaAlisNet { get; set; }
        public Nullable<decimal> OrtalamaSatisBrut { get; set; }
        public Nullable<decimal> OrtalamaSatisNet { get; set; }
        public Nullable<decimal> F7 { get; set; }
        public Nullable<decimal> F8 { get; set; }
        public Nullable<decimal> F9 { get; set; }
        public Nullable<decimal> F10 { get; set; }
        public string P2 { get; set; }
        public string P3 { get; set; }
        public string P4 { get; set; }
        public string P5 { get; set; }
        public string P6 { get; set; }
        public string P7 { get; set; }
        public string P8 { get; set; }
        public string P9 { get; set; }
        public string P10 { get; set; }
        public string BRM7 { get; set; }
        public string BRM8 { get; set; }
        public string BRM9 { get; set; }
        public string BRM10 { get; set; }
        public Nullable<bool> KomisyonUrunu { get; set; }
        public string Company_Code { get; set; }
        public Nullable<decimal> OrtalamaAF { get; set; }
    }
}
