//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE_PROCESS
    {
        public int ID { get; set; }
        public string IslemKodu { get; set; }
        public string IslemTarih { get; set; }
        public Nullable<int> GonderenDepoID { get; set; }
        public Nullable<int> AlanDepoID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string paraBirimi { get; set; }
        public Nullable<int> personelID { get; set; }
        public string Donem { get; set; }
        public Nullable<int> KayitPersonelID { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<decimal> Kur { get; set; }
        public Nullable<decimal> DolarKur { get; set; }
        public Nullable<decimal> EuroKur { get; set; }
        public Nullable<int> DepoSayimID { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public Nullable<int> EmirID { get; set; }
        public string Ekalan { get; set; }
        public string GirisTuru { get; set; }
        public Nullable<int> TCariID { get; set; }
        public Nullable<int> FaturaSatirID { get; set; }
        public Nullable<int> SiparisIDHFT { get; set; }
        public string Company_Code { get; set; }
    }
}
