//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE
    {
        public int ID { get; set; }
        public string Kodu { get; set; }
        public string DepoAdi { get; set; }
        public string Varsayilan { get; set; }
        public string Durumu { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string DepoGorevlisi { get; set; }
        public string EkBilgiler { get; set; }
        public string KayitT { get; set; }
        public string DegT { get; set; }
        public string defDepo { get; set; }
        public string FiyatTuru { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public string Rota { get; set; }
        public string Company_Code { get; set; }
        public Nullable<bool> Merkez { get; set; }
        public string BayiID { get; set; }
    }
}
