//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECHNICAL
    {
        public int ID { get; set; }
        public string ServisIslemNo { get; set; }
        public string Serino { get; set; }
        public string Durum { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Cinsi { get; set; }
        public string ServisYeri { get; set; }
        public string ServisTipi { get; set; }
        public string Onay { get; set; }
        public string Garanti { get; set; }
        public string Emanet { get; set; }
        public string Sikayet { get; set; }
        public string OnRapor { get; set; }
        public string Personel { get; set; }
        public string Tekniksyen { get; set; }
        public string Birim { get; set; }
        public string knt1 { get; set; }
        public string knt2 { get; set; }
        public string knt3 { get; set; }
        public string knt4 { get; set; }
        public string knt5 { get; set; }
        public string knt6 { get; set; }
        public string knt7 { get; set; }
        public string knt8 { get; set; }
        public string knt9 { get; set; }
        public string knt10 { get; set; }
        public string oAlan1 { get; set; }
        public string oAlan2 { get; set; }
        public string oAlan3 { get; set; }
        public string oAlan4 { get; set; }
        public string oAlan5 { get; set; }
        public string oAlan6 { get; set; }
        public string oAlan7 { get; set; }
        public string oAlan8 { get; set; }
        public string oAlan9 { get; set; }
        public string oAlan10 { get; set; }
        public string Tarih { get; set; }
        public string YenilemeTarih { get; set; }
        public string YenilemeDurum { get; set; }
        public string CariID { get; set; }
        public string isemriNo { get; set; }
        public string ArizaTespit { get; set; }
        public string OnarimRapor { get; set; }
        public string ServisNo { get; set; }
        public string Donem { get; set; }
        public Nullable<int> ServisID { get; set; }
        public Nullable<decimal> GenelToplam { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<decimal> BrutToplam { get; set; }
        public Nullable<decimal> NetToplam { get; set; }
        public Nullable<decimal> ToplamIskonto { get; set; }
        public Nullable<decimal> ToplamKdv { get; set; }
        public Nullable<decimal> TopHamMaliyet { get; set; }
        public string MYorumu { get; set; }
        public Nullable<int> MPuani { get; set; }
        public Nullable<int> OZelKodID { get; set; }
        public string Faturatipi { get; set; }
        public string SonDurumTarih { get; set; }
        public Nullable<decimal> q18Kdv { get; set; }
        public string kdvDH { get; set; }
        public Nullable<decimal> q8Kdv { get; set; }
        public Nullable<decimal> q1Kdv { get; set; }
        public Nullable<decimal> gIskonta { get; set; }
        public string CihazBarkod { get; set; }
        public string GarantiTipi { get; set; }
        public string IslemAraci { get; set; }
        public string PeriyodikBakim { get; set; }
        public Nullable<System.DateTime> TahminiOnarimTarih { get; set; }
        public Nullable<int> DepoID { get; set; }
        public Nullable<int> ServisOzelKod { get; set; }
        public Nullable<int> KayitPersonelID { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<decimal> Kur { get; set; }
        public Nullable<decimal> tMaliyet { get; set; }
        public Nullable<System.DateTime> DegT { get; set; }
        public Nullable<decimal> DolarKur { get; set; }
        public Nullable<decimal> EuroKur { get; set; }
        public string Durum2 { get; set; }
        public Nullable<System.DateTime> OnarimTarih { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public Nullable<decimal> ServisOdemesi { get; set; }
        public Nullable<System.DateTime> BakimBitisTarihi { get; set; }
        public string BakimPeriyodu { get; set; }
        public Nullable<decimal> ChfKur { get; set; }
        public Nullable<decimal> GbpKur { get; set; }
        public string BakimMetni { get; set; }
        public string TeslimTipi { get; set; }
        public Nullable<int> YetkiliID { get; set; }
        public Nullable<int> DServisCID { get; set; }
        public Nullable<System.DateTime> SonrakiBakimTarihi { get; set; }
        public Nullable<System.DateTime> BakimBaslangicTarihi { get; set; }
        public Nullable<bool> DenemeServis { get; set; }
        public Nullable<decimal> MKDkur { get; set; }
        public Nullable<int> CihazGarantisi { get; set; }
        public string ServisSekli { get; set; }
        public Nullable<int> PeriodGun { get; set; }
        public string ServisIcDis { get; set; }
        public Nullable<decimal> jpykur { get; set; }
        public string SanzimanNo { get; set; }
        public string YakitMiktar { get; set; }
        public Nullable<int> MotorHacmi { get; set; }
        public Nullable<int> Kilometre { get; set; }
        public string YakitTipi { get; set; }
        public string Vites { get; set; }
        public string Yil { get; set; }
        public string Company_Code { get; set; }
        public Nullable<System.DateTime> CihazSatisTarihi { get; set; }
        public Nullable<System.DateTime> GarantiBitisTarihi { get; set; }
        public Nullable<System.DateTime> GarantiBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> CihazMontajTarihi { get; set; }
        public string CihazAdi { get; set; }
        public string CihazAdresi { get; set; }
        public Nullable<int> BayiID { get; set; }
        public string ArizaKodu { get; set; }
    }
}
