//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaTeknopark_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetkiler
    {
        public int ID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string IslemSilme { get; set; }
        public string KasaIslem { get; set; }
        public string BankaIslem { get; set; }
        public string MesajGonderme { get; set; }
        public string ServisIslem { get; set; }
        public string RaporGorme { get; set; }
        public string Hatirlatma { get; set; }
        public string GelirGiderIslem { get; set; }
        public Nullable<bool> StokEG { get; set; }
        public Nullable<bool> StokSil { get; set; }
        public Nullable<bool> CariEG { get; set; }
        public Nullable<bool> CariSil { get; set; }
        public Nullable<bool> FaturaEG { get; set; }
        public Nullable<bool> FaturaSil { get; set; }
        public Nullable<bool> KasaEG { get; set; }
        public Nullable<bool> KasaSil { get; set; }
        public Nullable<bool> BankaEG { get; set; }
        public Nullable<bool> BankaSil { get; set; }
        public Nullable<bool> ServisEG { get; set; }
        public Nullable<bool> ServisSil { get; set; }
        public Nullable<bool> PersonelEG { get; set; }
        public Nullable<bool> PersonelSil { get; set; }
        public string YazdirSec { get; set; }
        public Nullable<short> FirmaID { get; set; }
        public string IslemGorme { get; set; }
        public string DepoGorme { get; set; }
        public Nullable<bool> CariBakiyeGor { get; set; }
        public Nullable<bool> StokBakiyeGor { get; set; }
        public Nullable<bool> CariKartGor { get; set; }
        public Nullable<bool> StokKartGor { get; set; }
        public Nullable<bool> KendiDepoMiktari { get; set; }
        public string PersonelGorme { get; set; }
        public Nullable<bool> SiparisPopup { get; set; }
        public Nullable<bool> SadeceKendiCarisi { get; set; }
        public Nullable<bool> RezervasyonSil { get; set; }
        public Nullable<bool> RezervasyonEG { get; set; }
        public Nullable<bool> UretimGorunumuKullan { get; set; }
        public Nullable<bool> EIrsaliyeKullan { get; set; }
        public Nullable<bool> DusukFiyatSatis { get; set; }
        public Nullable<bool> KrediKEG { get; set; }
        public Nullable<bool> KrediKSil { get; set; }
        public Nullable<bool> Sigortalar { get; set; }
        public Nullable<bool> MaasEG { get; set; }
        public Nullable<bool> MaasSil { get; set; }
        public Nullable<bool> FiyatDegistirme { get; set; }
        public string Company_Code { get; set; }
        public Nullable<bool> KasaDevri { get; set; }
        public Nullable<bool> HizliSatisMenusuGor { get; set; }
        public Nullable<bool> HizliSatisSime { get; set; }
        public Nullable<bool> KasaBankaBakGor { get; set; }
        public Nullable<bool> SadeceDoktor { get; set; }
    }
}
